version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movies
      POSTGRES_INITDB_ARGS: "--extension=uuid-ossp"
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_prepared_transactions=100", "-c", "fsync=off"]